Widget fullscreen
btovis/btovis.github.io pull request #237
Opened 2024-03-02 14:18 UTC by cshuenss

Make widgets fullscreenable.

- [ ] Make modal go to top of screen when opened
- [ ] Make graph scale with modal size
- [ ] Extend to other widgets?

2024-03-02 14:27 UTC, cshuenss commented
resolves #180

2024-03-02 15:18 UTC, George-Ogden commented
I'll have a look at this

2024-03-02 15:55 UTC, George-Ogden commented
@cshuenss I now get both charts to render fullscreen. There's an issue with the map but when I figure out what that is, we might be able to extend it.

2024-03-02 17:24 UTC, George-Ogden commented
I think this would be very useful to have on the map/table

2024-03-02 18:32 UTC, cshuenss commented
Thanks for the help. Will work on map/table fullscreening in the evening

2024-03-03 07:52 UTC, George-Ogden commented
This looks good - can you update please and I'll approve

2024-03-03 09:14 UTC, cshuenss commented
done @George-Ogden

2024-03-03 09:18 UTC, George-Ogden approved these changes
Is there an easy way to increase the number of rows in the table on fullscreen?

2024-03-03 09:18 UTC, George-Ogden commented on devfiles/src/ui/OptionsComp/PanelOptionsComp.tsx
> +                    console.log('asf');
Is this meant to be here?

2024-03-03 09:19 UTC, George-Ogden requested changes
There's the console.log issue. Is there a way to make the table display more rows in fullscreen?

2024-03-03 09:28 UTC, cshuenss commented
I did think about increasing table row count, but each row can be a variable height

The default of 10 works for widgets, could just make it 15 or something if fullscreen

2024-03-03 09:34 UTC, George-Ogden commented
> I did think about increasing table row count, but each row can be a variable height
> 
> The default of 10 works for widgets, could just make it 15 or something if fullscreen

I think that would be good. I also think 8 (or even 5) in a panel might be better so it looks less squashed.

2024-03-03 09:49 UTC, George-Ogden commented
Don't worry about the rows - I'll do it in #255

2024-03-03 09:49 UTC, George-Ogden approved these changes

2024-03-03 09:49 UTC, cshuenss commented
@George-Ogden just about to push the rows commit

2024-03-03 09:52 UTC, George-Ogden commented
> @George-Ogden just about to push the rows commit

That looks really good - I'm happy to keep it

2024-03-03 09:52 UTC, cshuenss commented
I'm busy until ~2pm so if there's any things you want to tweak and other things depend on it, it might be best to just make those changes while I'm not around

2024-03-03 09:53 UTC, merged